name: Deploy Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_LAMBDA_ROLE_ARN: arn:aws:iam::448792657937:role/lambda-fanout-role

jobs:
  deploy:
    name: Build and Deploy Lambdas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Deploy Metadata Extractor
      - name: Build and Push Metadata Extractor
        run: |
          cd lambda/metadata_extractor
          docker build -t ${{ steps.login-ecr.outputs.registry }}/metadata-extractor:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/metadata-extractor:${{ github.sha }}

      - name: Update Metadata Extractor Lambda
        run: |
          aws lambda update-function-code \
            --function-name metadata-extractor \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/metadata-extractor:${{ github.sha }}

      # Deploy Image Validator
      - name: Build and Push Image Validator
        run: |
          cd lambda/image_validator
          docker build -t ${{ steps.login-ecr.outputs.registry }}/image-validator:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/image-validator:${{ github.sha }}

      - name: Update Image Validator Lambda
        run: |
          aws lambda update-function-code \
            --function-name image-validator \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/image-validator:${{ github.sha }}